import Foundation

struct DexCompanionPairingPayload: Codable, Equatable {
    struct EnvironmentDescriptor: Codable, Equatable {
        let environmentId: String
        let label: String
    }

    struct AuthDescriptor: Codable, Equatable {
        let sessionCookieName: String
    }

    struct PairingTarget: Codable, Equatable {
        let httpBaseUrl: String
        let wsBaseUrl: String
    }

    struct PairingCredential: Codable, Equatable {
        let id: String
        let credential: String
        let label: String?
        let expiresAt: Date
    }

    let version: Int
    let issuedAt: Date
    let environment: EnvironmentDescriptor
    let auth: AuthDescriptor
    let target: PairingTarget
    let pairing: PairingCredential
}

enum DexCompanionQRValidationResult {
    case success(DexCompanionPairingPayload)
    case scanError(String)
}

func validateDexCompanionPairingPayload(_ code: String, now: Date = Date()) -> DexCompanionQRValidationResult {
    let trimmed = code.trimmingCharacters(in: .whitespacesAndNewlines)
    guard !trimmed.isEmpty else {
        return .scanError("QR code was empty.")
    }
    guard let data = trimmed.data(using: .utf8) else {
        return .scanError("QR code contains invalid text encoding.")
    }

    let decoder = JSONDecoder()
    decoder.dateDecodingStrategy = .iso8601

    guard let payload = try? decoder.decode(DexCompanionPairingPayload.self, from: data) else {
        return .scanError("Not a valid Dex desktop pairing payload.")
    }

    guard payload.version == 1 else {
        return .scanError("This pairing QR was generated by an incompatible Dex version.")
    }

    guard let httpURL = URL(string: payload.target.httpBaseUrl),
          let wsURL = URL(string: payload.target.wsBaseUrl),
          ["http", "https"].contains(httpURL.scheme?.lowercased() ?? ""),
          ["ws", "wss"].contains(wsURL.scheme?.lowercased() ?? "") else {
        return .scanError("Pairing payload is missing a valid Dex endpoint.")
    }

    guard !payload.environment.environmentId.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else {
        return .scanError("Pairing payload is missing the environment id.")
    }

    guard !payload.auth.sessionCookieName.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else {
        return .scanError("Pairing payload is missing the session cookie name.")
    }

    guard !payload.pairing.credential.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else {
        return .scanError("Pairing payload is missing the pairing credential.")
    }

    guard payload.pairing.expiresAt >= now else {
        return .scanError("This Dex desktop QR has expired. Generate a new one from the desktop app.")
    }

    return .success(payload)
}
