import Foundation

enum MacPairingQRValidationResult {
    case success(MacBridgePairingPayload)
    case scanError(String)
}

func validateMacPairingPayload(_ code: String, now: Date = Date()) -> MacPairingQRValidationResult {
    let trimmed = code.trimmingCharacters(in: .whitespacesAndNewlines)
    guard !trimmed.isEmpty else {
        return .scanError("QR code was empty.")
    }
    guard let data = trimmed.data(using: .utf8) else {
        return .scanError("QR code contains invalid text encoding.")
    }
    guard let payload = try? JSONDecoder().decode(MacBridgePairingPayload.self, from: data) else {
        return .scanError("Not a valid Litter Mac pairing payload.")
    }
    guard payload.v == 1 else {
        return .scanError("This pairing QR was generated by an incompatible bridge version.")
    }
    guard !payload.relay.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else {
        return .scanError("Pairing payload is missing the relay URL.")
    }
    if relayHostLooksLoopback(payload.relay) {
        return .scanError("This QR points to a local-only relay URL. Restart the Mac bridge and scan the fresh QR.")
    }
    guard !payload.sessionId.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else {
        return .scanError("Pairing payload is missing the session ID.")
    }
    let expiryDate = Date(timeIntervalSince1970: TimeInterval(payload.expiresAt) / 1000)
    guard expiryDate >= now else {
        return .scanError("This pairing QR has expired. Generate a new one from the Mac bridge.")
    }
    return .success(payload)
}

private func relayHostLooksLoopback(_ relay: String) -> Bool {
    guard let url = URL(string: relay), let host = url.host?.lowercased() else {
        return false
    }
    return host == "127.0.0.1" || host == "localhost" || host == "::1"
}
